version: 2
jobs:
  build:
    docker:
      - image: microsoft/powershell
        entrypoint: pwsh

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: pwsh -File tools/compile.ps1
