version: 2
jobs:
  build:
    docker:
      # - image: microsoft/powershell # ?? does it have python????
      - image: amacc/powershell-python
        entrypoint: pwsh

    steps:
      - checkout

      - run:
          name: Compile serverless.yml
          command: pwsh -File tools/compile.ps1

      - run:
          name: Deploy to AWS
          command: pwsh -File tools/deploy.ps1
