version: 2
jobs:
  build:
    docker:
      - image: microsoft/powershell # ?? does it have python????
      # - image: amacc/powershell-python
        entrypoint: pwsh

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Compile and Deploy
          command: pwsh -File tools/compile.ps1
